In [4]:
import numpy as np

In [8]:
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
arr = np.zeros(10)
arr[4] = 1  #

print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [20]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [31]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4]),)

In [48]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.random.random(9).reshape((3, 3))

array([[0.83022915, 0.64569239, 0.63167977],
       [0.14701512, 0.31817514, 0.53380311],
       [0.8296244 , 0.59593648, 0.52899071]])

In [76]:
a = np.random.random(100).reshape((10, 10))

# Mean of each column in matrix a
print(np.min(a))
  
# Mean of each row in matrix a
print(np.max(a))

0.0007604415590566349
0.9974753646319291


In [82]:
b = np.random.random(30)

np.mean(b)

0.4767691720432778

In [98]:
arr = np.zeros((5, 5))  # Create a 5x5 matrix of zeros

# Place the values 1, 2, 3, 4 just below the diagonal
np.fill_diagonal(arr[1:], [1, 2, 3, 4])

arr

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [109]:
matrix = np.random.rand(5, 5)

# Calculate the mean and standard deviation
mean = np.mean(matrix)
std = np.std(matrix)

# Normalize the matrix
normalized_matrix = (matrix - mean) / std

print("Original Matrix:\n", matrix)
print("\nNormalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[0.71585646 0.17574653 0.246529   0.46857383 0.59141035]
 [0.80904487 0.56354164 0.42276459 0.90561126 0.97261213]
 [0.64796499 0.99691814 0.23357747 0.44768334 0.92733544]
 [0.28575872 0.28042678 0.45978367 0.54935891 0.86358592]
 [0.86656355 0.35136939 0.13553627 0.56294915 0.92791076]]

Normalized Matrix:
 [[ 0.5192514  -1.49087592 -1.22744479 -0.40106048  0.05610027]
 [ 0.86607073 -0.04761871 -0.57154873  1.22546188  1.47481905]
 [ 0.26657968  1.56527874 -1.27564649 -0.47880861  1.30631276]
 [-1.08144353 -1.1012874  -0.43377481 -0.10040262  1.06905617]
 [ 1.08013801 -0.83726027 -1.64052646 -0.04982382  1.30845396]]


In [111]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array1, array2)

print(common_values)

[3 4 5]


In [113]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(random_vector)

print("Original Vector:\n", random_vector)
print("\nSorted Vector:\n", sorted_vector)

Original Vector:
 [0.4130186  0.88427933 0.74162299 0.58609227 0.87890567 0.31304661
 0.61532009 0.23320375 0.95798498 0.49069249]

Sorted Vector:
 [0.23320375 0.31304661 0.4130186  0.49069249 0.58609227 0.61532009
 0.74162299 0.87890567 0.88427933 0.95798498]


In [115]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Original Vector:\n", random_vector)

Original Vector:
 [0.         0.40402372 0.44340495 0.4258655  0.68018954 0.34717778
 0.43528319 0.39116078 0.4978826  0.5738955 ]


In [16]:
matrix = np.random.rand(6, 6)  # 4 rows, 5 columns

# Calculate the row means
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the matrix
centered_matrix = matrix - row_means

print("Original Matrix:\n", matrix)
print("\nCentered Matrix:\n", centered_matrix)

Original Matrix:
 [[0.30248704 0.81258376 0.8668437  0.71775138 0.74947404 0.54719483]
 [0.24469584 0.61148488 0.49425    0.62051279 0.63161708 0.37269193]
 [0.57091505 0.69078413 0.3733037  0.26160851 0.66948756 0.86727102]
 [0.05300366 0.10323909 0.23014562 0.17193283 0.89393973 0.93502912]
 [0.0419467  0.04760294 0.5135387  0.33887399 0.9224298  0.48602486]
 [0.65495328 0.00809486 0.95400245 0.16159671 0.97099524 0.58505212]]

Centered Matrix:
 [[-0.36356875  0.14652797  0.2007879   0.05169559  0.08341825 -0.11886096]
 [-0.25117958  0.11560946 -0.00162542  0.12463737  0.13574166 -0.12318349]
 [-0.00131328  0.1185558  -0.19892463 -0.31061982  0.09725923  0.2950427 ]
 [-0.34487801 -0.29464259 -0.16773606 -0.22594884  0.49605806  0.53714744]
 [-0.34978946 -0.34413322  0.12180254 -0.05286218  0.53069363  0.09428869]
 [ 0.09917084 -0.54768759  0.39822    -0.39418573  0.4152128   0.02926968]]


In [119]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Using np.argsort (returns indices of sorted array)
largest_indices = np.argsort(Z)[-n:]
largest_values = Z[largest_indices]

# Using np.argpartition (partitions the array around the nth largest element)
largest_values_partition = Z[np.argpartition(Z, -n)[-n:]]

print("Largest Values (argsort):\n", largest_values)
print("\nLargest Values (argpartition):\n", largest_values_partition)

Largest Values (argsort):
 [9995 9996 9997 9998 9999]

Largest Values (argpartition):
 [9995 9997 9996 9999 9998]


In [121]:
matrix = np.random.randint(1, 10, size=(5, 3))  # Random integers between 1 and 9

# Replace elements > 4 with their squares
squared_matrix = np.where(matrix > 4, matrix**2, matrix)

print("Original Matrix:\n", matrix)
print("\nSquared Matrix:\n", squared_matrix)

Original Matrix:
 [[1 6 7]
 [6 2 6]
 [7 5 1]
 [9 1 9]
 [2 2 7]]

Squared Matrix:
 [[ 1 36 49]
 [36  2 36]
 [49 25  1]
 [81  1 81]
 [ 2  2 49]]
